# Generated by Django 5.2.6 on 2025-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_team', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('age', models.IntegerField()),
                ('drive_years', models.CharField(max_length=100)),
            ],
        ),
    ]
