# Generated by Django 5.2.6 on 2025-09-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_helmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='helmets/'),
        ),
    ]
