# Generated by Django 5.2.6 on 2025-09-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_helmet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='helmets',
            field=models.ManyToManyField(blank=True, to='main_app.helmet'),
        ),
    ]
